version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: peace-postgres
    restart: always
    environment:
      POSTGRES_USER: nutri_login
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: peace_db
    ports:
      - "5430:5432"
    volumes:
      - peace-data:/var/lib/postgresql/data

volumes:
  peace-data: